# Select what we should cache
cache:
  paths:
  - app/vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

test:php5.4:
  image: php:5.4
  script:
  - app/vendor/bin/phpunit

test:php5.5:
  image: php:5.5
  script:
  - app/vendor/bin/phpunit

test:php5.6:
  image: php:5.6
  script:
  - app/vendor/bin/phpunit

test:php7:
  image: php:7
  script:
  - app/vendor/bin/phpunit
